export const InitialStreamDataValues ={
    id:            "",
    user_id:       "",
    user_login:    "",
    user_name:     "",
    game_id:       "",
    game_name:     "",
    type:          "",
    title:         "",
    viewer_count:  0,
    started_at:    "",
    language:      "",
    thumbnail_url: "",
    tag_ids:       [],
    tags:          [],
    is_mature:     false,
}